services:
    app:
        build: ./docker-resources/php-fpm/
        volumes:
            - ./:/var/www/html
        networks:
            - invoiceplane_net

    web:
        build: ./docker-resources/apache/
        ports:
            - "80:80"
        volumes:
            - ./:/usr/local/apache2/htdocs
        networks:
            - invoiceplane_net
        depends_on:
            - database
            - app

    node:
        image: node:20-alpine
        command: sh /docker-entrypoint.sh
        working_dir: /app
        ports:
            - "5173:5173"
        volumes:
            - ./:/app
            - ./docker-resources/node/scripts/entrypoint.sh:/docker-entrypoint.sh:ro
        networks:
            - invoiceplane_net

    database:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_HOST: "%"
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - invoiceplane_net
            
volumes:
    mysql_data:

networks:
    invoiceplane_net:
        driver: bridge